changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 💥 Breaking Changes
      labels:
        - Semver-Major
        - breaking-change
    - title: 🚀 New Features
      labels:
        - Semver-Minor
        - enhancement
    - title: '🐛 Bug Fixes'
      labels:
        - 'bug'
        - 'fix'
        - 'bugfix'
        - 'hotfix'
    - title: 📦 Dependencies
      labels:
        - dependencies
    - title: 🎲 Other Changes
      labels:
        - "*"
